export const SET_REGISTER_MOBILE_NUMBER = 'SET_REGISTER_MOBILE_NUMBER';

export const VALIDATE_USER = 'VALIDATE_USER';
export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS';
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE';

export const PRODUCT = 'PRODUCT';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const SELECTED_EVENT = 'SELECTED_EVENT';
export const ADD_PRODUCT = 'ADD_PRODUCT';

